name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Buildar projeto
        run: npm run build

      # Troque "build" por "dist" ou "out" se for o caso
      - name: Deploy para branch "deploy"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist
          clean: true
          commit-message: "Deploy automático [skip ci]"
